version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dbpostgres
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    image: core:tag
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
    depends_on:
      - db
volumes:
  postgres_data:
